version: '3'
services:
  minio:
    hostname: minio
    image: minio/minio
    command: server /data/minio --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes: 
      - ./minio-data:/data/minio
  presto:
    hostname: presto
    image: 'starburstdata/presto:350-e.7'
    container_name: presto
    ports:
      - '8080:8080'
    volumes:
      - './presto/presto-cli-0.253-executable.jar:/usr/bin/presto'
      - './presto/minio.properties:/usr/lib/presto/etc/catalog/minio.properties'
  hadoop:
    hostname: hadoop-master
    image: 'prestodb/hive3.1-hive:5'
    container_name: hadoop-master
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
    volumes:
      - './hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml'
  mc-job:
    image: 'minio/mc:latest'
    environment:
      MC_HOST_presto: "http://minio:minio123@minio:9000"
    volumes:
      - './minio/data:/minio'
    depends_on:
      - minio
    entrypoint: |
      /bin/bash -c "
      /usr/bin/mc mb --quiet presto/customer-data-text;
      /usr/bin/mc mb --quiet presto/customer-data-orc;
      /usr/bin/mc mirror minio/customer-data-text presto/customer-data-text;
      "
